In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
a.shape


(3, 3)

In [5]:
b = np.array([[11,22,33],[44,55,66],[77,88,99]])

In [6]:
b.shape


(3, 3)

In [7]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [25]:
c = np.stack([a, b],-1)

In [26]:
c


array([[[ 1, 11],
        [ 2, 22],
        [ 3, 33]],

       [[ 4, 44],
        [ 5, 55],
        [ 6, 66]],

       [[ 7, 77],
        [ 8, 88],
        [ 9, 99]]])

In [27]:
c.shape

(3, 3, 2)

In [13]:
c1 = np.stack([a, b])

In [14]:
c1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

In [15]:
c1.shape

(2, 3, 3)

In [16]:
c[:,:1]


array([[[ 1,  2,  3]],

       [[11, 22, 33]]])

In [17]:
c[:,:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [18]:
c[:,:,1]

array([[ 2,  5,  8],
       [22, 55, 88]])

In [19]:
c[:,:,2]

array([[ 3,  6,  9],
       [33, 66, 99]])

In [20]:
c1[0,:,:]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
c1[:,:,0]

array([[ 1,  4,  7],
       [11, 44, 77]])

In [28]:
c[:,:,0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
c.shape

(2, 3, 3)